name: Build & Bundle
on: push

jobs:
    build:
        name: 'Build'
        runs-on: ubuntu-22.04
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Build
              run: yarn build

    bundle:
        name: 'Bundling and Create Release'
        runs-on: ubuntu-22.04
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn

            - name: Bundle
              run: yarn bundle

            - name: Zipping
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r build.zip dist

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: plumbs-client
                  path: build.zip

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: build.zip
